# Generated by Django 3.1.2 on 2021-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210318_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion Web'),
        ),
    ]
